carlossg/docker-maven

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carlossg/docker-maven/22)
=> Add info on using local .m2 copy

README.md, ibmjava-8/Dockerfile, ibmjava-8/mvn-entrypoint.sh, ibmjava-8/onbuild/Dockerfile, ibmjava-8/settings-docker.xml, ibmjava-9/Dockerfile, ibmjava-9/mvn-entrypoint.sh, ibmjava-9/onbuild/Dockerfile, ibmjava-9/settings-docker.xml
I think this could accommodate what I was getting at in #25. That said, I'm ok with you closing the PR and saying no go as well.
Cheers,
-Rob
=> closes #25 - adding support for ibmjava 8 and 9

jdk-8/Dockerfile
Added missing curly braces to MAVEN_VERSION in url
=> Added missing curly braces to MAVEN_VERSION

jdk-9-slim/Dockerfile, jdk-9/Dockerfile
I was build this dockerfile on arm64 architecture just use FROM arm64v8/openjdk:jdk-9 and successed
=> add support for arm64

README.md, ibmjava-8-alpine/Dockerfile, ibmjava-8/Dockerfile, ibmjava-9-alpine/Dockerfile, ibmjava-9/Dockerfile, jdk-7-alpine/Dockerfile, jdk-7-slim/Dockerfile, jdk-7/Dockerfile, jdk-8-alpine/Dockerfile, jdk-8-slim/Dockerfile, jdk-8/Dockerfile, jdk-9-slim/Dockerfile, jdk-9/Dockerfile
It's a source of confusion for most users
Fixes #35 #32 #24 #11 
@tianon WDYT would this be a reasonable change for the next release of the official images?
=> Remove volume declaration

README.md
=> Add multi-stage build example

amazoncorretto-11/Dockerfile, amazoncorretto-11/mvn-entrypoint.sh, amazoncorretto-11/settings-docker.xml
Adding build of [amazoncorretto:11](https://hub.docker.com/_/amazoncorretto).
Resolves #104
=> Add amazon corretto 11 build

README.md
- Fix a missing parentheses
- Update the new plugin version of `go-offline`
Cheers!
=> Typo + New Plugin Version

jdk-11-openj9/Dockerfile, jdk-11-openj9/mvn-entrypoint.sh, jdk-11-openj9/settings-docker.xml, jdk-8-openj9/Dockerfile, jdk-8-openj9/mvn-entrypoint.sh, jdk-8-openj9/settings-docker.xml, publish.sh
=> add dockerfiles for openj9

.github/github-action-template.yaml, .github/workflows/adoptopenjdk-11-openj9.yml, .github/workflows/adoptopenjdk-11.yml, .github/workflows/adoptopenjdk-14-openj9.yml, .github/workflows/adoptopenjdk-14.yml, .github/workflows/adoptopenjdk-8-openj9.yml, .github/workflows/adoptopenjdk-8.yml, .github/workflows/amazoncorretto-11.yml, .github/workflows/amazoncorretto-8.yml, .github/workflows/azulzulu-11.yml, .github/workflows/ibmjava-8-alpine.yml, .github/workflows/ibmjava-8.yml, .github/workflows/openjdk-11-slim.yml, .github/workflows/openjdk-11.yml, .github/workflows/openjdk-14.yml, .github/workflows/openjdk-15.yml, .github/workflows/openjdk-8-slim.yml, .github/workflows/openjdk-8.yml, .github/workflows/windows.yml, common.sh, generate-stackbrew-library.sh, github-action-generation.sh, github-action.sh, publish.sh
=> chore: centralize dir selection

amazoncorretto-11/Dockerfile, amazoncorretto-8/Dockerfile
remove cache files to reduce the size of the layer.
659MB -> 464MB
=> feat: remove yum cache

openjdk-14/Dockerfile, openjdk-15/Dockerfile
in openjdk images due to upgrade to oracle linux slim
Fixes #165
=> fix: find is no longer available

.gitignore, tests/Dockerfile, tests/maven.Tests.ps1, tests/tests.bats
=> test: use the tag

openjdk-14/Dockerfile, openjdk-15/Dockerfile, openjdk-16/Dockerfile, tests/tests.bats
=> feat: add git to openjdk images

README.md, generate-stackbrew-library.sh, github-action.ps1
missing replacements
from https://github.com/carlossg/docker-maven/pull/238
=> feat: maven 3.8.4

eclipse-temurin-11-alpine/Dockerfile, eclipse-temurin-16-alpine/Dockerfile, eclipse-temurin-17-alpine/Dockerfile
for better caching and consistency with other images
=> chore: move up the apk install

amazoncorretto-11/Dockerfile, amazoncorretto-17/Dockerfile, amazoncorretto-8/Dockerfile, azulzulu-11/Dockerfile, azulzulu-17/Dockerfile, eclipse-temurin-11/Dockerfile, eclipse-temurin-16/Dockerfile, eclipse-temurin-17/Dockerfile, eclipse-temurin-8/Dockerfile, ibm-semeru-11-focal/Dockerfile, ibm-semeru-17-focal/Dockerfile, ibmjava-8/Dockerfile, microsoft-openjdk-11-ubuntu/Dockerfile, microsoft-openjdk-16-ubuntu/Dockerfile, microsoft-openjdk-17-ubuntu/Dockerfile, openjdk-11-slim/Dockerfile, openjdk-17-slim/Dockerfile, openjdk-17/Dockerfile, openjdk-8-slim/Dockerfile
so new maven versions can reuse the first layers
=> chore: optimize image layers

.github/workflows/openjdk-18-slim.yml, .github/workflows/openjdk-18.yml, README.md, openjdk-18-slim/Dockerfile, openjdk-18-slim/mvn-entrypoint.sh, openjdk-18-slim/settings-docker.xml, openjdk-18/Dockerfile, openjdk-18/mvn-entrypoint.sh, openjdk-18/settings-docker.xml
=> feat: openjdk 18

.github/workflows/_template.yml, tags-for-dir.sh
=> build: multiline strings seem fixed now

tests/maven.Tests.ps1, tests/pom.xml
to fix windows image test issues
=> test: force surefire version

.github/workflows/_template.yml
=> chore: upgrade cosign

eclipse-temurin-11/Dockerfile, eclipse-temurin-19/Dockerfile
cause the build to fail
https://github.com/docker-library/official-images/pull/14223#issuecomment-1466783251
=> fix: ensure RUN failures

eclipse-temurin-11/Dockerfile
=> feat: Update to maven 3.9.1

.github/workflows/eclipse-temurin-20-alpine.yml, .github/workflows/eclipse-temurin-20.yml, README.md, eclipse-temurin-20-alpine/Dockerfile, eclipse-temurin-20-alpine/mvn-entrypoint.sh, eclipse-temurin-20-alpine/settings-docker.xml, eclipse-temurin-20/Dockerfile, eclipse-temurin-20/mvn-entrypoint.sh, eclipse-temurin-20/settings-docker.xml, tests/pom.xml
Add eclipse-temurin-20 maven images.
=> eclipse-temurin-20 - add eclipse-temurin-20 maven images.

.github/workflows/amazoncorretto-20-debian-slim.yml, .github/workflows/amazoncorretto-20.yml, README.md, amazoncorretto-20-debian-slim/Dockerfile, amazoncorretto-20/Dockerfile, amazoncorretto-20/mvn-entrypoint.sh, amazoncorretto-20/settings-docker.xml
Had to update source/target in tests from 1.7 to 8
=> Add amazon corretto 20

.github/workflows/amazoncorretto-21-debian.yml, README.md, amazoncorretto-21-debian/Dockerfile
Let me know if I've missed anything and I'll change it.
=> Add Amazon Corretto 21 debian image

.github/workflows/sapmachine-21.yml, README.md, sapmachine-21/Dockerfile
Adds support for sapmachine 21 as base JDK.
=> Adds support for sapmachine 21

common.sh
if we are not building the latest maven version
=> chore: do not push some tags

.github/workflows/_template.yml, .gitmodules
=> test: switch bats action to bats-core/bats-action

.github/workflows/graalvm-community-17.yml, .github/workflows/graalvm-community-21.yml, .github/workflows/oracle-graalvm-17.yml, .github/workflows/oracle-graalvm-21.yml, README.md, common.sh, generate-stackbrew-library.sh, graalvm-community-17/Dockerfile, graalvm-community-21/Dockerfile, oracle-graalvm-17/Dockerfile, oracle-graalvm-21/Dockerfile, tests/tests.bats
This PR adds images that use GraalVM Community and Oracle GraalVM for JDK 17 and 21.
Fixes #242
=> Add GraalVM images

amazoncorretto-11-windowsservercore/Dockerfile, amazoncorretto-17-windowsservercore/Dockerfile, amazoncorretto-8-windowsservercore/Dockerfile
=> chore: bump amazon corretto windows

amazoncorretto-11-debian/Dockerfile, amazoncorretto-17-debian-maven-4/Dockerfile, amazoncorretto-17-debian/Dockerfile, amazoncorretto-21-debian-maven-4/Dockerfile, amazoncorretto-21-debian/Dockerfile, amazoncorretto-23-debian-maven-4/Dockerfile, amazoncorretto-23-debian/Dockerfile, amazoncorretto-8-debian/Dockerfile
Fixes carlossg/docker-maven#519
=> chore: check sha256sum for corretto.key

amazoncorretto-11-debian/Dockerfile, amazoncorretto-17-debian-maven-4/Dockerfile, amazoncorretto-17-debian/Dockerfile, amazoncorretto-21-debian-maven-4/Dockerfile, amazoncorretto-21-debian/Dockerfile, amazoncorretto-23-debian-maven-4/Dockerfile, amazoncorretto-23-debian/Dockerfile, amazoncorretto-8-debian/Dockerfile, publish.sh
=> chore: update corretto.key sha

.github/workflows/_template_windows.yml, amazoncorretto-11-windowsservercore/Dockerfile, amazoncorretto-17-windowsservercore-maven-4/Dockerfile, amazoncorretto-17-windowsservercore/Dockerfile, amazoncorretto-8-windowsservercore/Dockerfile, azulzulu-11-windowsservercore/Dockerfile, azulzulu-17-windowsservercore-maven-4/Dockerfile, azulzulu-17-windowsservercore/Dockerfile, github-action.ps1
Since windows-2019 is gone on 30th June 2025
See https://github.com/actions/runner-images/issues/12045
=> Build on windows-2025

amazoncorretto-24-al2023/Dockerfile
=> fix: remove tar and which from amazoncorretto-24-al2023

amazoncorretto-11-debian/Dockerfile, amazoncorretto-17-debian-maven-4/Dockerfile, amazoncorretto-17-debian/Dockerfile, amazoncorretto-21-debian-maven-4/Dockerfile, amazoncorretto-21-debian/Dockerfile, amazoncorretto-24-debian-maven-4/Dockerfile, amazoncorretto-24-debian/Dockerfile, amazoncorretto-8-debian/Dockerfile
(This should fix the build failures we've been seeing :eyes:)
=> Update checksum for corretto.key

tests/tests.bats
new versions.
Prevents full builds on each new version added
=> test: legacy checks should not affect

amazoncorretto-21-maven-4/Dockerfile, amazoncorretto-21/Dockerfile, amazoncorretto-24-maven-4/Dockerfile, amazoncorretto-25-maven-4/Dockerfile, tests/tests.bats
=> fix: find is missing in amazoncorretto 24,25
