jdk-7/Dockerfile
jdk-8/Dockerfile

All downloads should happen over SSL (and even better verified in some way),
otherwise the images can easily get compromised.

Force downloads to be over SSL

---

jdk-7/Dockerfile
jdk-8/Dockerfile

This avoids putting undue strain on the archive.apache.org infra and
also is a simple workaround for the following (which I've been seeing on
recent builds):
curl: (60) SSL certificate problem: unable to get local issuer
certificate
More details here: http://curl.haxx.se/docs/sslcerts.html
curl performs SSL certificate verification by default, using a "bundle"
of Certificate Authority (CA) public keys (CA certs). If the default
bundle file isn't adequate, you can specify an alternate file
using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
the bundle, the certificate verification probably failed due to a
problem with the certificate (it might be expired, or the name might
not match the domain name in the URL).
If you'd like to turn off curl's …

Switch from archive.apache.org to an explicit (known reliable) mirror

---

jdk-8/mvn-entrypoint.sh
jdk-9/mvn-entrypoint.sh
tests/tests.bats

Modify the entry-point script to emit a warning when unable to write to `$MAVEN_CONFIG` directory and then carry on. This should allow for the previous `docker.inside` behavior to once again function correctly.

Prevent failure when not running as root.

---

jdk-7-slim/Dockerfile
jdk-7-slim/mvn-entrypoint.sh
jdk-7-slim/settings-docker.xml
jdk-8-slim/Dockerfile
jdk-8-slim/mvn-entrypoint.sh
jdk-8-slim/settings-docker.xml
jdk-9-slim/Dockerfile
jdk-9-slim/mvn-entrypoint.sh
jdk-9-slim/settings-docker.xml

There is an ongoing work to provide a slimmer version of the debian based image, openjdk already has a version based on this one, so it could be interesting to have a slim version of the maven too.

Add jdk-*-slim versions

---

README.md

added:
This is a base image that you can extend, so it has the bare minimum packages needed. If you add custom package(s) to the `Dockerfile`, then you can build your local Docker image like this:
docker build --tag my_local_maven:3.5.0-jdk-8_rpm .

section about docker build -t local_image

---

generate-stackbrew-library.sh

I tried to match your `branch` logic, but not sure I got it 100% correct (and not 100% sure how you're using those bits either :innocent:).
I'm happy to make the official-images PR for this once it's merged too, if you'd like! :+1:
Closes #45

Update "generate-stackbrew-library.sh" to generate appropriate Architectures values (and use the new RFC 2822-based format)

---

jdk-8-alpine/Dockerfile

This fixes a bug discussed in #53 and introduced in b7f10a80f, apparently a typo while fixing issue #46.  In this PR, the base image is set to `openjdk:8-jdk-alpine` instead of `openjdk:8-jre-alpine`, as the latter does not include `javac`, needed to build java code.  
I have tested this fix with a container that builds a java library using maven.  Without the fix, the build fails with the error message shown in #53; with the fix, it completes successfully.

Fix #53: use a -jdk- base image rather than -jre-

---

README.md
jdk-11-slim/Dockerfile
jdk-11-slim/mvn-entrypoint.sh
jdk-11-slim/settings-docker.xml
jdk-11/Dockerfile
jdk-11/mvn-entrypoint.sh
jdk-11/settings-docker.xml

Based on PR #66 and fixes #79.
This needs to wait for https://github.com/docker-library/openjdk/pull/186 since it requires openjdk 11 docker images.

Add jdk-11 and jdk-11-slim images

---

azulzulu-11/Dockerfile
azulzulu-11/mvn-entrypoint.sh
azulzulu-11/settings-docker.xml

This is maven 3.6.0 on another java-11 variant. I cribbed from the jdk-11 base image to get started. There aren't many changes to speak of...
1. Dockerfile has minor changes to keep up with the ubuntu base image.
2. mvn-entrypoint.sh and settings-docker.xml are unchanged from their jdk-11/ versions.
I ran tests this way, which seemed to pass.
TAG=jdk-11 bats tests

Maven 3.6.0 on azul j11

---

generate-stackbrew-library.sh

This will automatically include the appropriate `Constraints: !aufs` for Oracle Linux-based images (and has no effect otherwise).

Add "Constraints:" where appropriate

---

README.md

Starting with Maven 3, you typically don't need to run `mvn clean install` - in fact, both `clean` and `install` can usually be discarded of.
This PR reflects that in the documentation of this container.

Do not suggest to run clean or install goals

---

.github/workflows/main.yml
README.md
windows/Dockerfile.windows-amazoncorretto-11
windows/Dockerfile.windows-amazoncorretto-8
windows/Dockerfile.windows-azulzulu-11
windows/Dockerfile.windows-jdk-11
windows/Dockerfile.windows-jdk-11-nanoserver
windows/Dockerfile.windows-jdk-11-openj9
windows/Dockerfile.windows-jdk-13
windows/Dockerfile.windows-jdk-14
windows/Dockerfile.windows-jdk-8-nanoserver
windows/Dockerfile.windows-jdk-8-openj9

Some of the JDKs have issues with nanoserver, so
I updated them to versions that should work with
nanoserver.
Updated the README to have the correct
paths to the Dockerfiles for Windows.
Added openj9 versions for jdk8 and jdk11. Currently
there are some issues with openj9 for nanoserver, so
I did not add those variants.

Update windows maven to 3.6.3 and upgrade some JDK's

---

openjdk-14/Dockerfile
openjdk-15/Dockerfile
openjdk-16/Dockerfile

although nothing changes as they were already switched to by openjdk:1?-jdk

feat: lock images to oraclelinux8

---

README.md

Replace `-u 1000` by the actual id of the user.
See https://man7.org/linux/man-pages/man1/id.1.html
Tested:
On Mac OS and Linux

Update README.md to use effective user id instead of 1000

---

.github/workflows/libericaopenjdk-17-alpine.yml
.github/workflows/libericaopenjdk-17.yml
.gitignore
README.md
common.sh
github-action-generation.sh
libericaopenjdk-17-alpine/Dockerfile
libericaopenjdk-17-alpine/mvn-entrypoint.sh
libericaopenjdk-17-alpine/settings-docker.xml
libericaopenjdk-17/Dockerfile
libericaopenjdk-17/mvn-entrypoint.sh
libericaopenjdk-17/settings-docker.xml

This adds Liberica 17 CentOS and Alpine as requested in #278 
I had to modify github-action-generation.sh to work on Linux:
1. Override LC_COLLATE to preserve the sort ordering in other.yml
2. Switch references to gsed to sed. It looks like you're overriding the path to sed in command.sh and using sed about half the time, so I'm hoping this doesn't break on Mac, but either of these changes certainly could.
Happy to back them out, but I assume other submitters are occasionally working around these issues.
Thanks!

Liberica 17

---

README.md

https://github.com/infosiftr/docker-library-docs/blob/master/openjdk/deprecated.md

docs: openjdk images are deprecated

---

.github/workflows/_template.yml

This PR intends to address the Node.js 12 deprecation warnings by updating various actions, and mitigates the `set-ouput` warning by switching the syntax.

Update actions to silence Node.js 12 warnings and deprecations

---

amazoncorretto-11-debian-slim/Dockerfile
amazoncorretto-17-debian-slim/Dockerfile
amazoncorretto-19-debian-slim/Dockerfile
amazoncorretto-20-debian-slim/Dockerfile
amazoncorretto-8-debian-slim/Dockerfile

@carlossg I saw the comment on https://github.com/docker-library/official-images/pull/14308#issuecomment-1496758237 about passing downloaded keys via gpg so I've tried to do that here in this PR.
I also changed the corretto-20-debian image to install `java-20-amazon-correto-jdk` -- I think it was accidentally installing 19.

Verify corretto apt key & make corretto-20-debian image install the java-20 package

---

.github/workflows/amazoncorretto-11-debian.yml
.github/workflows/amazoncorretto-17-debian.yml
.github/workflows/amazoncorretto-19-debian.yml
.github/workflows/amazoncorretto-20-debian.yml
.github/workflows/amazoncorretto-8-debian.yml
README.md
amazoncorretto-11-debian/Dockerfile
amazoncorretto-17-debian/Dockerfile
amazoncorretto-19-debian/Dockerfile
amazoncorretto-20-debian/Dockerfile
amazoncorretto-8-debian/Dockerfile
common.sh
generate-stackbrew-library.sh
tests/tests.bats

I've done the following in this PR:
- renamed `amazoncorretto-*-debian-slim` to just `amazoncorretto-*-debian`
- added way to specify extra tag suffixes for an image in Dockerfile via an ARG
- added tagging corretto debian variants with `bullseye` suffix so one can pin to that to guard against surprise upgrade to next stable
- pruned arches not supported by corretto apt repo
Let me know what you think of all this; of course, I'm happy to make any changes you suggest.

Rename corretto debian variants

---

generate-stackbrew-library.sh

@carlossg can you see if this works for the moment? Unfortunately, my current dev env is not set up properly to run `generate_stackbrew_library.sh` 😔.
I can try to make a cleaner fix later that doesn't assume the order of the architectures (probably something like put them in a bash array, loop through them and only take what we need).

Remove s390x for amazoncorretto-*-debian actually

---

tests/tests.bats

image before running tests
as other images depend on the eclipse-temurin one

test: build the base eclipse-temurin-11

---

.github/workflows/amazoncorretto-11-al2023.yml
.github/workflows/amazoncorretto-17-al2023.yml
.github/workflows/amazoncorretto-20-al2023.yml
.github/workflows/amazoncorretto-8-al2023.yml
README.md
amazoncorretto-11-al2023/Dockerfile
amazoncorretto-17-al2023/Dockerfile
amazoncorretto-20-al2023/Dockerfile
amazoncorretto-8-al2023/Dockerfile
tests/tests.bats

Adding Amazon Corretto images based on Amazon Linux 2023.
- Added `findutils` package, as `find` was not available
- There is **no** `20-al2023` tag in https://hub.docker.com/_/amazoncorretto/tags?page=1&name=20-al2023, therefore I had to use `20-al2023-generic` (there is also **no** `8-al2023-generic`, `11-al2023-generic` and `17-al2023-generic`), so upstream tagging is a bit of inconsistent.
Issue: #392

feat: Add Amazon Corretto images based on Amazon Linux 2023

---

.github/workflows/amazoncorretto-21.yml
README.md
amazoncorretto-21/Dockerfile

Since Amazon Corretto team published new images based on Java 21 (https://github.com/corretto/corretto-docker/pull/179 ), this PR introduces similar amazoncorreto-21 flavour as there already is for older Java versions.
I looked also at the al2023 variant, but there are no `generic` corretto images, so while it could be done using `headless`, I'm not sure whether that's desirable.
Let me know if anything is missing from this PR. Thanks

Add Amazon Corretto 21 image

---

.github/workflows/amazoncorretto-21-al2023.yml
README.md
amazoncorretto-21-al2023/Dockerfile

- Add image containing Corretto 21 and AL2023
- There was no corretto:21-al2023-generic variant so I chose corretto:21-al2023 per the guidance [on the dockerhub Corretto page](https://hub.docker.com/_/amazoncorretto) under Image Variants

Add Corretto21-AL2023

---

.github/workflows/_template.yml
README.md

as 1.11 breaks bats-action
https://github.com/bats-core/bats-action/pull/4

test: lock bats version to 1.10.0

---

README.md

Freenode is largely deprecated[1] by Libera.Chat.
Fixes #485
1 https://en.wikipedia.org/wiki/Freenode#Ownership_change_and_conflict

docs(README): update IRC service and add web link support

---

.github/workflows/amazoncorretto-11-alpine.yml
.github/workflows/amazoncorretto-17-alpine.yml
.github/workflows/amazoncorretto-21-alpine.yml
.github/workflows/amazoncorretto-23-alpine.yml
.github/workflows/amazoncorretto-8-alpine.yml
README.md
amazoncorretto-11-alpine/Dockerfile
amazoncorretto-17-alpine/Dockerfile
amazoncorretto-21-alpine/Dockerfile
amazoncorretto-23-alpine/Dockerfile
amazoncorretto-8-alpine/Dockerfile
tests/tests.bats

Opening this PR to support Alpine-based Corretto images, based on the associated [upstream Amazon maintained Corretto Alpine images](https://github.com/corretto/corretto-docker).
I added installed packages through apk to match the debian images, however I don't think these should be included and should be left to users to extend the image if they want additional utilities like curl on the image, particularly since it increases the complexity for maintaining this project. If that isn't controversial, I'll happily amend my commit to not add any additional packages.
Closes #269
I've tested building all versions of the images, as well as using Maven to build Java projects for Java 8 and 17. Worked as expected for me.

Add Dockerfiles for alpine-based images

---

amazoncorretto-11-windowsservercore/Dockerfile
amazoncorretto-17-windowsservercore-maven-4/Dockerfile
amazoncorretto-17-windowsservercore/Dockerfile
amazoncorretto-8-windowsservercore/Dockerfile
azulzulu-11-windowsservercore/Dockerfile
azulzulu-17-windowsservercore-maven-4/Dockerfile
azulzulu-17-windowsservercore/Dockerfile
eclipse-temurin-17-maven-4/Dockerfile
eclipse-temurin-17/Dockerfile

@slawekjaranowski 
Probably better to split the upgrade and missing keys
https://github.com/carlossg/docker-maven/pull/551 need to be rebased when merged

Use closer download link and add `84789D24DF77A32433CE1F079EB80E92EB2135B1` key and update JDKs for windows due to latest download URL

---

generate-stackbrew-library.sh

as corretto does not support them

chore: remove non amd/arm corretto debian images
